# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0002_auto_20160703_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('stripe_id', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.State')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SubscriptionPlan')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
