# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('steps', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('floors', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('elevation', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('calories_burned', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('water', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('validic_id', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Source'),
        ),
    ]
