# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biometrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('validic_id', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('blood_calcium', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('blood_chromium', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('blood_folic_acid', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('blood_magnesium', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('blood_potassium', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('blood_sodium', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('blood_vitamin_b12', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('blood_zinc', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('creatine_kinase', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('crp', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('diastolic', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ferritin', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('hdl', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('hscrp', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('il6', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ldl', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('resting_heartrate', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('systolic', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('testosterone', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_cholestrol', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('tsh', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('uric_acid', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('vitamin_d', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('white_cell_count', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('spo2', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('validic_id', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('c_peptide', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fasting_plasma_glucose_test', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('hba1c', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('insulin', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('oral_glucose_tolerance_test', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('random_plasma_glucose_test', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('relationship_to_meal', models.CharField(blank=True, max_length=100, null=True)),
                ('triglyceride', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('blood_glucose', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('validic_id', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('activity_category', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('intensity', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('validic_id', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('water', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('meal', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('validic_id', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('awake', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('deep', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('light', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('rem', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('times_woken', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('total_sleep', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('validic_id', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('free_mass', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('mass_weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='calories_burned',
            new_name='calories',
        ),
    ]
