# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20160604_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometrics',
            name='validic_id',
        ),
        migrations.RemoveField(
            model_name='diabetes',
            name='validic_id',
        ),
        migrations.RemoveField(
            model_name='fitness',
            name='validic_id',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='validic_id',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='validic_id',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='validic_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='validic_id',
        ),
        migrations.AlterField(
            model_name='biometrics',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='routine',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weight',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
