# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_auto_20160626_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fitness',
            name='activity_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='broker.ActivityCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitness',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='broker.ActivityType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitness',
            name='intensity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='broker.Intensity'),
            preserve_default=False,
        ),
    ]
